### ISSUE TITLE
it is not possible to download from the website d3scene.com

### ISSUE THREAD

**Issue by VokerTO** [SterilliumD3Scene/ZombieWorldUnity#1]
Site d3scene.com it is impossible to download for free registration does not pass, I enter the data when registering, I wait 120 seconds and the button is not active, I noticed in the right corner "This site key is not enabled for the invisible captcha."

**Comment by Alfred-GitHub1** [comment]
join the discord and write me.
https://discord.gg/pj5x7vk

**Comment by Alfred-GitHub1** [comment]
captcha problem is fixed.
